import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * 수동 사이드바 — 보안 여정 단계(페이즈)로 그룹핑하되, 각 Part를 이름 있는
 * 카테고리로 감싸 파트/섹션 구분을 유지한다(autogenerated 로 하위 문서는 자동 확장).
 *   시작하기 · 보안 여정 · 솔루션 패키지
 *   → 기초 / 예방 / 운영 / 거버넌스·고급 / 부록   (각 Part 는 named 하위 카테고리)
 */
const part = (label: string, dirName: string) => ({
  type: 'category' as const,
  label,
  collapsed: true,
  items: [{type: 'autogenerated' as const, dirName}],
});

const sidebars: SidebarsConfig = {
  guideSidebar: [
    'intro',
    'common-problems',
    'security-journey',
    {
      type: 'category',
      label: '🚀 솔루션 패키지',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'solutions'}],
    },
    {
      type: 'category',
      label: '기초 (Foundations)',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'foundations'}],
    },
    {
      type: 'category',
      label: '예방 (Protect)',
      collapsed: false,
      items: [
        part('자격증명 & 접근 관리', 'identity-access'),
        part('인프라 & 네트워크 보안', 'infrastructure-network'),
        part('데이터 보호', 'data-protection'),
        part('애플리케이션 & 워크로드', 'application-workload'),
      ],
    },
    {
      type: 'category',
      label: '운영 (Detect · Respond · Recover)',
      collapsed: false,
      items: [
        part('탐지 & 대응', 'detection-response'),
        part('복원력 & 랜섬웨어', 'resilience'),
      ],
    },
    {
      type: 'category',
      label: '거버넌스 & 고급',
      collapsed: false,
      items: [
        part('거버넌스 & 컴플라이언스', 'governance-compliance'),
        part('고급 & 신기술', 'advanced'),
      ],
    },
    {
      type: 'category',
      label: '부록',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'references'}],
    },
  ],
};

export default sidebars;
